dbConfig:
  host: localhost
  port: 27017
  dbName: sms

server:
  port: 3000

authSevice:
  url: login.sharemyscreen.local

devService:
  url: dev.sharemyscreen.local

test:
  dbConfig:
    dbName: sms-test