dbConfig:
  host: localhost
  port: 27017
  dbName: sms

server:
  port: 3000

devService:
  url: dev.sharemyscreen.local
loginService:
  url: login.sharemyscreen.local
apiService:
  url: api.sharemyscreen.local

test:
  dbConfig:
    dbName: sms-test

logFile: request.log
googleApiKey: AIzaSyCp0VnNyEznPykPPhzA660Y1ZGdf0WGUxI