dbConfig:
  host: localhost
  port: 27017
  dbName: sms

server:
  port: 3000

devService:
  url: dev.sharemyscreen.fr
loginService:
  url: login.sharemyscreen.fr
apiService:
  url: api.sharemyscreen.fr

test:
  dbConfig:
    dbName: sms-test

logFile: request.log
googleApiKey: AIzaSyCp0VnNyEznPykPPhzA660Y1ZGdf0WGUxI